In [88]:
!pip install -q rpy2

In [89]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


# Creating a Matrix

## Creating a Matrix

In [90]:
# We've learned about vectors which allow us to store indexed elements.
# A matrix will allow us to have a 2-dimensional data structure which contains elements consisting of the same data type.

In [91]:
%%R

v <- 1:10
matrix(v)

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


In [92]:
%%R

matrix(v,nrow=2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [93]:
%%R

matrix(1:12, byrow=TRUE, nrow=4)


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [94]:
%%R

matrix(1:12,byrow = FALSE,nrow=4)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


## Creating Matrices from Vectors

In [95]:
%%R

goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

stocks <- c(goog,msft)
stocks

 [1] 450 451 452 445 468 230 231 232 236 228


In [96]:
%%R

stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)
stock.matrix

     [,1] [,2] [,3] [,4] [,5]
[1,]  450  451  452  445  468
[2,]  230  231  232  236  228


## Naming Matrices

In [97]:
# We can do this similarly to the names() function for vectors,
# but in this case we define colnames() and rownames().

In [98]:
%%R

days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')

colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

stock.matrix


     Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228


# Factor and Categorical Matrices

In [99]:
# factor() function: use for creating categorical matrices. (this idea is sometimes also known as creating dummy variable)

# if you wanted to assign an order while using the factor() function,
# you can pass in the arguments ordered=True and the pass in the levels= and pass in a vector in the order you want the levels to be in.

In [100]:
%%R

temps <- c('cold','med','cold','med','hot','hot','cold')

In [101]:
%%R

summary(temps)

   Length     Class      Mode 
        7 character character 


In [102]:
%%R

fact.temp <- factor(temps, ordered=TRUE, levels= c('cold','med','hot'))
fact.temp

[1] cold med  cold med  hot  hot  cold
Levels: cold < med < hot


In [103]:
%%R

summary(fact.temp)

cold  med  hot 
   3    2    2 


# Matrix Arithmetic


In [104]:
# We can perform element by element mathematical operations on a matrix with a scalar (single number) just like we could with vectors

In [105]:
%%R

mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50


In [106]:
%%R

# Multiplication
2*mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    2    4    6    8   10   12   14   16   18    20
[2,]   22   24   26   28   30   32   34   36   38    40
[3,]   42   44   46   48   50   52   54   56   58    60
[4,]   62   64   66   68   70   72   74   76   78    80
[5,]   82   84   86   88   90   92   94   96   98   100


In [107]:
%%R

# Division (reciprocal)
1/mat

           [,1]       [,2]       [,3]       [,4]       [,5]       [,6]
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
           [,7]       [,8]       [,9]      [,10]
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000


In [108]:
%%R

# Division
mat/2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5    1  1.5    2  2.5    3  3.5    4  4.5     5
[2,]  5.5    6  6.5    7  7.5    8  8.5    9  9.5    10
[3,] 10.5   11 11.5   12 12.5   13 13.5   14 14.5    15
[4,] 15.5   16 16.5   17 17.5   18 18.5   19 19.5    20
[5,] 20.5   21 21.5   22 22.5   23 23.5   24 24.5    25


In [109]:
%%R

# Power
mat ^ 2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81   100
[2,]  121  144  169  196  225  256  289  324  361   400
[3,]  441  484  529  576  625  676  729  784  841   900
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521  1600
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401  2500


## Comparison operators with matrices

In [110]:
# We can similarly perform comparison operations across an entire matrix to return a matrix of logicals

In [111]:
%%R

mat > 17

      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE


## Matrix Arithmetic with multiple matrices

In [112]:
# We can use multiple matrices with arithmetic as well

In [113]:
%%R

mat + mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    2    4    6    8   10   12   14   16   18    20
[2,]   22   24   26   28   30   32   34   36   38    40
[3,]   42   44   46   48   50   52   54   56   58    60
[4,]   62   64   66   68   70   72   74   76   78    80
[5,]   82   84   86   88   90   92   94   96   98   100


In [114]:
%%R

mat / mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    1    1    1    1    1    1    1    1     1
[2,]    1    1    1    1    1    1    1    1    1     1
[3,]    1    1    1    1    1    1    1    1    1     1
[4,]    1    1    1    1    1    1    1    1    1     1
[5,]    1    1    1    1    1    1    1    1    1     1


In [115]:
%%R

mat*mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81   100
[2,]  121  144  169  196  225  256  289  324  361   400
[3,]  441  484  529  576  625  676  729  784  841   900
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521  1600
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401  2500


In [116]:
# True Matrix Multiplication

In [117]:
%%R

mat2 <- matrix(1:9, nrow=3)

In [118]:
%%R

# True Matrix Multiplication
mat2 %*% mat2

     [,1] [,2] [,3]
[1,]   30   66  102
[2,]   36   81  126
[3,]   42   96  150


# Matrix Operations

In [119]:
%%R

# Prices
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

# Put vectors into matrix
stocks <- c(goog,msft)
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)

# Name matrix
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

# Display
stock.matrix

     Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228


In [120]:
%%R

colSums(stock.matrix)

Mon Tue Wed Thu Fri 
680 682 684 681 696 


In [121]:
%%R

rowMeans(stock.matrix)

 GOOG  MSFT 
453.2 231.4 


In [122]:
%%R

# Doesn't really make sense for stocks, but just to show how it works
rowSums(stock.matrix)

GOOG MSFT 
2266 1157 


We can also do other mathematical operations, check this [reference](https://chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://cran.r-project.org/doc/contrib/Short-refcard.pdf) for all functions available.


# Matrix Selection and Indexing

In [123]:
#  we have two dimensions to work with, we'll use a comma to separate our indexing for each dimension.
# example.matrix[rows,columns]

In [124]:
%%R

mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    2    3    4    5    6    7    8    9    10
[2,]   11   12   13   14   15   16   17   18   19    20
[3,]   21   22   23   24   25   26   27   28   29    30
[4,]   31   32   33   34   35   36   37   38   39    40
[5,]   41   42   43   44   45   46   47   48   49    50


In [125]:
%%R

# Grab first row
mat[1,]

 [1]  1  2  3  4  5  6  7  8  9 10


In [126]:
%%R

#Grab first column
mat[,1]

[1]  1 11 21 31 41


In [127]:
%%R

# Grab a center square of:
# 15,16
# 25,26

mat[2:3,5:6]

     [,1] [,2]
[1,]   15   16
[2,]   25   26
