In [41]:
!pip install -q rpy2

In [42]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


# Using list()

In [43]:
# Lists will allow us to store a variety of data structures under a single variable.
# This means we could store a vecor,matrix, data frame, etc. under a single list.

In [44]:
%%R

# Create a vector
v <- c(1,2,3,4,5)

# Create a matrix
m <- matrix(1:10,nrow=2)

# Create a data frame
df <- women


In [45]:
%%R

v

[1] 1 2 3 4 5


In [46]:
%%R

m

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [47]:
%%R

df

   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164


In [48]:
# We can use the list() to combine all the data structures

In [49]:
%%R

li <- list(v,m,df)
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164



In [50]:
# You will notice that the list() assigned numbers to each of the objects in the list, but we can also assign names

In [51]:
%%R

li <- list(sample_vec = v,sample_mat = m, sample_df = df)
li

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164



# Selecting objects from a list

In [52]:
# You can use bracket notation to show objects in a list, and double brackets to actually grab the objects form the list

In [53]:
%%R

# Single brackets
li[1] # By index

$sample_vec
[1] 1 2 3 4 5



In [54]:
%%R

# By name
li['sample_vec']

$sample_vec
[1] 1 2 3 4 5



In [55]:
%%R

# Notice the type!
class(li['sample_vec'])

[1] "list"


In [56]:
%%R

# Use double brackets to actually grab the items
li[['sample_vec']]

[1] 1 2 3 4 5


In [57]:
%%R

# Can also use $ notation
li$sample_vec

[1] 1 2 3 4 5


In [58]:
# You can also index on top of this once you've selected the object from the list

In [59]:
%%R

li[['sample_vec']][1] # Second set of indexing

[1] 1


In [60]:
%%R

li[['sample_mat']]

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [61]:
%%R

li[['sample_mat']][1,]

[1] 1 3 5 7 9


In [62]:
%%R

li[['sample_mat']][1:2,1:2]

     [,1] [,2]
[1,]    1    3
[2,]    2    4


In [63]:
%%R

li[['sample_df']]['height']

   height
1      58
2      59
3      60
4      61
5      62
6      63
7      64
8      65
9      66
10     67
11     68
12     69
13     70
14     71
15     72


# Combining lists

In [64]:
# Lists can hold other lists! You can also combine lists using the combine function c()

In [69]:
%%R

double_list <- c(li,li)
double_list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164



In [71]:
%%R

str(double_list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
